-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 04 Des 2024 pada 05.42
-- Versi server: 8.0.40-0ubuntu0.24.04.1
-- Versi PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tanamore_db`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `garden_plants`
--

CREATE TABLE `garden_plants` (
  `garden_plant_id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `plant_id` varchar(255) NOT NULL,
  `nickname` varchar(255) DEFAULT NULL,
  `planted_at` date DEFAULT NULL,
  `garden_description` text,
  `garden_status` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Struktur dari tabel `image`
--

CREATE TABLE `image` (
  `image_id` varchar(255) NOT NULL,
  `plant_id` varchar(255) NOT NULL,
  `type` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Struktur dari tabel `plant_diseases`
--

CREATE TABLE `plant_diseases` (
  `disease_id` varchar(255) NOT NULL,
  `plant_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `disease_name` varchar(255) NOT NULL,
  `symptoms` text,
  `causes` text,
  `treatment` text,
  `prevention_tips` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data untuk tabel `plant_diseases`
--

INSERT INTO `plant_diseases` (`disease_id`, `plant_id`, `disease_name`, `symptoms`, `causes`, `treatment`, `prevention_tips`) VALUES
('disease_00', 'plant_21', 'Apple Scab', 'Apple scab ditandai dengan bercak-bercak gelap pada daun, buah, dan batang, yang dapat menyebabkan kerusakan serius pada tanaman dan mengurangi kualitas buah.', 'Jamur Venturia inaequalis', 'Untuk mengatasi apple scab, penting untuk menggunakan fungisida yang efektif. Pastikan penyemprotan dilakukan sesuai dengan petunjuk yang tertera pada kemasan, terutama saat cuaca lembap. Selain itu, buang daun yang terinfeksi untuk mencegah penyebaran penyakit. Pemangkasan tanaman untuk meningkatkan sirkulasi udara juga sangat dianjurkan. ', 'Jaga sirkulasi udara di sekitar tanaman dengan memangkas cabang yang rimbun dan pastikan tidak ada genangan air di area tanam. Pilih varietas apel yang tahan terhadap penyakit ini sebagai langkah pencegahan yang efektif.'),
('disease_01', 'plant_21', 'Black Rot on Apple', 'Black rot ditandai dengan pembusukan pada buah dan bercak hitam di daun. Penyakit ini dapat mengurangi hasil panen dan menurunkan kualitas buah.', 'Jamur Botryosphaeria obtusa', 'Segera buang buah yang terinfeksi dan gunakan fungisida sesuai dosis yang disarankan. Aplikasi fungisida harus dilakukan sebelum gejala muncul, terutama saat tanaman sedang berbunga dan berbuah. Melakukan pemeriksaan rutin pada tanaman juga penting untuk mendeteksi gejala lebih awal.', 'Pemangkasan yang baik dan sanitasi area tanam sangat penting. Pastikan untuk membersihkan puing-puing tanaman yang terinfeksi dan menjaga alat berkebun tetap bersih untuk mencegah penyebaran patogen.'),
('disease_02', 'plant_21', 'Cedar Apple Rust', 'Cedar apple rust ditandai dengan bercak oranye pada daun dan dapat menyebabkan kerusakan serius serta mengurangi hasil panen.', 'Jamur Gymnosporangium juniperi-virginianae', 'Pemangkasan pada cabang yang terkena dan penggunaan fungisida yang efektif dapat membantu mengendalikan penyakit ini. Aplikasikan fungisida pada awal musim tanam dan ulangi setiap beberapa minggu saat kondisi memungkinkan infeksi.', 'Hindari penanaman dekat pohon cedar yang dapat menjadi inang bagi jamur. Jaga kelembapan tanaman agar tidak terlalu lembap dan pastikan ada cukup ruang antar tanaman untuk meningkatkan sirkulasi udara.'),
('disease_03', 'plant_21', 'Healthy Apple', 'Tanaman apel Anda dalam kondisi sehat, tumbuh dengan baik dan bebas dari tanda-tanda penyakit. Dengan perawatan yang tepat, Anda dapat menikmati hasil panen yang melimpah.', NULL, 'Untuk menjaga kesehatan tanaman apel, lakukan penyiraman yang konsisten terutama di musim panas, tetapi hindari genangan air. Pastikan tanaman mendapatkan sinar matahari minimal 6-8 jam per hari. Pemupukan secara berkala dengan pupuk organik akan membantu meningkatkan kualitas buah. Jangan lupa untuk memangkas cabang yang mati atau terlalu rapat untuk meningkatkan sirkulasi udara. Lakukan pemantauan rutin untuk mendeteksi hama atau gejala penyakit sejak dini.', NULL),
('disease_04', NULL, 'Background Without Leaves', 'null', 'null', 'null', 'null'),
('disease_05', 'plant_18', 'Healthy Blueberry', 'Blueberry Anda dalam kondisi sehat dan siap untuk tumbuh optimal. Kesehatan tanaman yang baik ini menunjukkan bahwa Anda telah melakukan langkah-langkah perawatan yang benar.', NULL, 'Pastikan blueberry mendapatkan pH tanah yang sesuai antara 4,5 hingga 5,5. Penyiraman harus dilakukan secara teratur, terutama saat buah mulai terbentuk. Gunakan mulsa untuk menjaga kelembapan tanah dan mencegah pertumbuhan gulma. Pemupukan dengan pupuk yang kaya nitrogen di awal musim tanam akan membantu pertumbuhan vegetatif yang baik. Jagalah tanaman dari hama dengan menggunakan insektisida alami jika diperlukan.', NULL),
('disease_06', NULL, 'Cherry Powdery Mildey', 'Penyakit ini ditandai dengan lapisan putih berbubuk pada daun, yang menyebabkan daun layu dan mengurangi hasil buah.', 'Jamur Podosphaera atau Erysiphe', 'Terapkan fungisida saat gejala pertama kali muncul dan ulangi sesuai petunjuk. Penting untuk memangkas daun yang terinfeksi dan membersihkan area sekitar tanaman untuk mengurangi sumber infeksi. Pastikan kelembapan tanah terjaga agar tidak berlebih.', 'Sirkulasi udara yang baik dapat dicapai dengan memberikan jarak antar tanaman. Hindari penyiraman pada sore hari dan pilih pagi hari untuk menyiram agar air tidak tertinggal di daun.'),
('disease_07', NULL, 'Healthy Cherry', 'Tanaman cherry Anda sehat dan tumbuh dengan baik, menunjukkan pertumbuhan yang kuat dan tidak ada tanda-tanda infeksi.', NULL, 'Berikan penyiraman yang cukup, terutama saat cuaca panas dan selama pembentukan buah. Gunakan pupuk yang mengandung kalium dan fosfor untuk meningkatkan kualitas buah. Pemangkasan pada akhir musim dingin dapat membantu mendorong pertumbuhan baru dan meningkatkan sirkulasi udara di dalam kanopi tanaman. Pastikan tanaman cherry Anda terlindungi dari hama dengan memantau secara berkala dan menggunakan metode pencegahan alami.', NULL),
('disease_08', NULL, 'Corn Cercospora Leaf Spot Gray Leaf Spot', 'Cercospora leaf spot ditandai dengan bercak-bercak gelap pada daun yang dapat menyebar dan menyebabkan daun mengering. Penyakit ini dapat mengurangi fotosintesis dan hasil panen.', 'Jamur Cercospora zeae-maydis', 'Untuk mengatasi Cercospora leaf spot pada jagung, penting untuk menerapkan fungisida yang efektif segera setelah gejala pertama kali muncul, dan ulangi aplikasi sesuai dengan instruksi pada label produk. Pemangkasan daun yang terinfeksi juga harus dilakukan untuk mengurangi penyebaran patogen ke daun sehat. Selain itu, rotasi tanaman dapat membantu memutus siklus hidup jamur dan mengurangi akumulasi patogen di dalam tanah.', 'Untuk mencegah penyakit ini, pastikan ada jarak yang cukup antar tanaman guna meningkatkan sirkulasi udara, yang pada gilirannya akan mengurangi kelembapan di sekitar tanaman. Hindari juga penyiraman yang berlebihan, terutama di sore hari, agar kelembapan pada daun dapat cepat kering dan tidak mendukung pertumbuhan jamur.'),
('disease_09', NULL, 'Corn Common Rust', 'Common rust ditandai dengan bercak-bercak merah-cokelat yang muncul di daun dan dapat mengurangi hasil panen. Jika tidak diatasi, penyakit ini dapat mengakibatkan kehilangan hasil yang signifikan.', 'Jamur Puccinia sorghi', 'Dalam menangani common rust, aplikasi fungisida yang direkomendasikan harus dilakukan saat gejala pertama muncul, diikuti dengan pengelolaan kelembapan di sekitar tanaman untuk memastikan tidak terlalu tinggi, karena kondisi lembap mendukung pertumbuhan jamur.', 'Untuk mencegah infeksi, sangat disarankan untuk melakukan rotasi dengan varietas jagung yang lebih tahan terhadap common rust. Selain itu, lakukan pengawasan dan pemantauan secara rutin untuk mendeteksi gejala penyakit lebih awal, sehingga penanganan dapat dilakukan dengan cepat dan efektif.'),
('disease_10', NULL, 'Corn Northern Leaf Blight', 'Northern leaf blight ditandai dengan bercak-bercak panjang yang berwarna abu-abu hingga hitam pada daun, yang dapat menyebabkan kerusakan serius pada tanaman dan menurunkan hasil panen.', 'Jamur Exserohilum turcicum', 'Untuk mengatasi northern leaf blight pada jagung, aplikasikan fungisida yang efektif pada tahap awal gejala agar dapat menghentikan perkembangan penyakit. Penting juga untuk melakukan pemangkasan dan menjaga kebersihan area tanam dengan membuang bagian tanaman yang terinfeksi untuk mengurangi akumulasi patogen.', 'Sebagai langkah pencegahan, tanam varietas jagung yang telah terbukti tahan terhadap penyakit ini untuk meminimalkan risiko infeksi. Pastikan juga ada cukup jarak antar tanaman agar sirkulasi udara tetap baik, sehingga kelembapan dapat dikontrol dan risiko terjadinya infeksi dapat diminimalkan.'),
('disease_11', NULL, 'Corn Healthy', 'Jagung Anda dalam kondisi sehat dan berkembang dengan baik. Dengan perawatan yang tepat, Anda dapat berharap untuk mendapatkan hasil panen yang melimpah.', NULL, 'Lakukan penyiraman secara rutin, terutama pada fase pertumbuhan awal dan saat cob corn mulai terbentuk. Pastikan tanaman mendapatkan sinar matahari penuh untuk pertumbuhan optimal. Gunakan pupuk nitrogen pada awal musim tanam untuk meningkatkan pertumbuhan vegetatif. Pemangkasan daun yang mati atau tidak sehat akan membantu menjaga kesehatan tanaman. Jaga jarak tanam yang cukup untuk meningkatkan sirkulasi udara dan mengurangi risiko penyakit.', NULL),
('disease_12', 'plant_12', 'Black Rot on Grape', 'Black rot ditandai dengan pembusukan pada buah dan bercak hitam di batang, yang dapat menurunkan kualitas dan hasil panen.', 'Jamur Botrytis cinerea', 'Buang bagian tanaman yang terinfeksi dan gunakan fungisida sesuai dosis yang disarankan. Penyemprotan harus dilakukan sebelum gejala muncul, terutama selama fase pembungaan dan berbuah. Pemantauan rutin sangat penting untuk mendeteksi infeksi lebih awal.', 'Sanitasi area tanam dan pemangkasan sangat penting untuk mencegah penyebaran penyakit. Pastikan untuk membersihkan puing-puing tanaman yang terinfeksi dan menjaga kelembapan tanah seimbang.'),
('disease_13', 'plant_12', 'Esca (Black Measles) on Grape', 'Esca ditandai dengan bercak hitam pada daun, pembusukan kayu, dan buah, yang dapat mengakibatkan kehilangan hasil yang signifikan.', 'Jamur Phaeomoniella chlamydospora', 'Buang tanaman yang terinfeksi dan perbaiki sirkulasi udara dengan memangkas cabang yang rimbun. Gunakan fungisida sesuai rekomendasi untuk pengendalian penyakit. Melakukan pemantauan dan pemangkasan secara berkala dapat menjaga kesehatan tanaman.', 'Hindari kelembapan tinggi dengan tidak menyiram pada sore hari dan menjaga kebersihan kebun. Tanam varietas anggur yang lebih tahan terhadap penyakit ini, serta lakukan rotasi tanaman untuk mencegah infeksi pada tahun-tahun mendatang.'),
('disease_14', 'plant_12', 'Grape Leaf Blight', 'Grape Leaf Blight adalah penyakit yang menyebabkan kerusakan pada daun anggur, ditandai dengan bercak cokelat atau hitam dan penguningan daun. Infeksi yang parah dapat mengurangi hasil panen dan kualitas buah.', 'Jamur patogen, seperti Phomopsis viticola dan Botrytis cinerea', 'Penting untuk memangkas bagian tanaman yang terinfeksi guna meningkatkan sirkulasi udara dan mencegah penyebaran lebih lanjut. Penggunaan fungisida yang sesuai harus dilakukan saat gejala awal muncul, dan pastikan bahwa tanah memiliki drainase yang baik untuk mengurangi kelembaban berlebih. Selain itu, menjaga kebersihan kebun dengan menghilangkan daun dan sisa tanaman yang terinfeksi sangatlah penting. Praktik rotasi tanaman dan penanaman varietas yang tahan terhadap penyakit juga dapat membantu.', NULL),
('disease_15', 'plant_12', 'Healthy Grape', 'Tanaman anggur yang sehat memiliki pertumbuhan yang kuat dengan batang yang kokoh dan cabang yang rimbun. Daunnya berwarna hijau cerah, menunjukkan kesehatan yang baik, dan tidak terdapat bercak, kerusakan, atau gejala infeksi. Buah anggur muncul dalam kelompok yang subur, biasanya berwarna ungu, hijau, atau merah, tergantung pada varietasnya. Tanaman ini juga memiliki akar yang kuat dan sistem perakaran yang baik, yang mendukung pertumbuhan dan penyerapan nutrisi secara optimal.', NULL, 'Lakukan pemangkasan secara teratur guna menghilangkan bagian tanaman yang mati atau terinfeksi, serta meningkatkan sirkulasi udara dan penetrasi cahaya matahari. Penyiraman harus dilakukan dengan baik, terutama selama musim panas, dengan memastikan tanah sedikit kering di antara penyiraman. Pemberian pupuk seimbang yang kaya nitrogen, fosfor, dan kalium sangat dianjurkan untuk mendukung pertumbuhan yang sehat. Selain itu, lakukan pengendalian hama secara rutin dengan memeriksa adanya kutu daun, ulat, atau serangga lain yang dapat merusak tanaman.', NULL),
('disease_16', NULL, 'Orange Huanglongbing (HLB) / Citrus Greening', 'Huanglongbing (HLB) adalah penyakit yang sangat merusak tanaman jeruk, yang ditandai dengan gejala seperti daun menguning, buah yang kecil dan asimetris, serta penurunan hasil yang signifikan.', 'Bakteri Candidatus Liberibacter yang ditularkan melalui serangga vektor, terutama Diaphorina citri (psyllid jeruk).', 'Perawatan tanaman yang terinfeksi HLB meliputi memangkas pohon yang terinfeksi dan menghancurkan semua bagian yang terkontaminasi, serta menggunakan pestisida untuk mengendalikan populasi psylid guna mencegah penyebaran bakteri. Penanaman varietas jeruk yang tahan terhadap HLB juga merupakan langkah yang bijaksana.', 'Melakukan inspeksi rutin terhadap tanaman untuk mendeteksi gejala awal dan menjaga kebersihan di sekitar kebun dengan menghilangkan sumber serangga vektor. Penggunaan umpan perangkap untuk mengontrol serangga psylid juga dapat membantu mengurangi risiko infeksi.'),
('disease_17', NULL, 'Peach Bacterial Spot', 'Peach Bacterial Spot adalah penyakit yang ditandai dengan munculnya bercak-bercak air yang dapat berkembang menjadi luka pada buah persik, yang menyebabkan penurunan kualitas dan nilai jual buah.', 'Bakteri Xanthomonas arboricola, yang dapat menginfeksi melalui luka pada daun atau buah, serta kondisi kelembaban yang tinggi.', 'Untuk merawat tanaman persik yang terinfeksi, hilangkan bagian tanaman yang terinfeksi guna mencegah penyebaran lebih lanjut, serta gunakan fungisida atau bakterisida yang sesuai untuk mengontrol infeksi. Selain itu, menjaga kelembaban tanah agar tidak berlebihan adalah langkah penting.', 'Memangkas tanaman secara teratur untuk meningkatkan sirkulasi udara dan cahaya matahari sangat dianjurkan. Menghindari penyiraman yang berlebihan dan menggunakan irigasi yang tepat untuk menjaga kelembaban tanah juga dapat membantu. Memilih varietas persik yang lebih tahan terhadap penyakit ini akan memberikan perlindungan tambahan.'),
('disease_18', NULL, 'Healthy Peach', 'Tanaman persik yang sehat memiliki batang yang tegak dan kuat dengan daun yang lebar dan hijau segar. Daun-daun ini tidak memiliki bercak, kerusakan, atau gejala infeksi, menandakan bahwa tanaman dalam kondisi prima. Buah persik biasanya tumbuh dengan baik, memiliki ukuran yang seragam, warna yang menarik, dan tekstur kulit yang halus. Akar tanaman juga berkembang dengan baik, memastikan penyerapan air dan nutrisi yang optimal.', NULL, 'Pastikan tanaman mendapatkan penyiraman yang cukup, terutama selama periode pembentukan buah, tetapi hindari genangan air. Pemberian nutrisi menggunakan pupuk yang sesuai dengan kebutuhan tanaman persik, terutama pada awal musim tanam dan menjelang pembungaan, juga sangat penting. Perlindungan dari hama perlu dilakukan dengan pemantauan rutin untuk mendeteksi hama seperti buah lalat dan kutu daun, serta menggunakan pestisida organik jika diperlukan. Pemangkasan juga dianjurkan untuk membentuk kanopi yang baik dan meningkatkan sirkulasi udara di antara cabang.', NULL),
('disease_19', NULL, 'Pepper Bell Bachterial Spot', 'Pepper Bell Bacterial Spot adalah penyakit yang ditandai dengan bercak-bercak berair yang muncul pada daun, batang, dan buah cabai, yang dapat menyebabkan penurunan hasil dan kualitas buah.', 'Bakteri Xanthomonas campestris, yang dapat menyebar melalui kontak langsung, alat pertanian yang terkontaminasi, dan air irigasi.', 'Untuk merawat tanaman cabai yang terinfeksi, hilangkan bagian tanaman yang terinfeksi dan gunakan bakterisida untuk mengontrol penyebaran bakteri. Menjaga kelembaban tanah yang seimbang dan tidak berlebihan juga penting.', 'Melakukan rotasi tanaman, menjaga jarak antar tanaman untuk meningkatkan sirkulasi udara, serta membersihkan alat pertanian secara teratur untuk menghindari penyebaran patogen. Pilihlah varietas cabai yang tahan terhadap penyakit ini sebagai langkah pencegahan tambahan.'),
('disease_20', NULL, 'Healthy Pepper Bell', 'Tanaman cabai bell yang sehat memiliki pertumbuhan yang subur dengan batang yang kuat dan kokoh. Daun-daunnya berwarna hijau cerah dan lebar, tanpa bercak atau tanda infeksi. Buah cabai bell tumbuh dengan baik, memiliki ukuran yang seragam, warna yang cerah, dan kulit yang halus. Tanaman ini juga menunjukkan sirkulasi udara yang baik di antara cabang-cabangnya, serta akar yang berkembang dengan baik, memastikan penyerapan nutrisi dan air yang optimal.', NULL, 'Penyiraman secara teratur sangat dibutuhkan, terutama saat buah mulai terbentuk, sambil memastikan tidak terjadi genangan air. Berikan pupuk yang kaya akan kalium dan fosfor untuk mendukung pembentukan buah yang baik. Lakukan rotasi tanaman setiap musim tanam untuk mengurangi risiko penyakit dan hama. Selain itu, cek secara rutin untuk serangan hama seperti kutu daun atau belalang, dan ambil langkah pencegahan jika ditemukan.', NULL),
('disease_21', 'plant_19', 'Potato Early Blight', 'Potato Early Blight adalah penyakit yang ditandai dengan bercak-bercak cokelat pada daun, yang dapat menyebabkan daun menguning dan rontok, serta menurunkan hasil panen.', 'Jamur Alternaria solani, yang berkembang biak di kondisi lembab dan dapat menyebar melalui air hujan dan angin.', 'Untuk mengendalikan penyakit ini, lakukan pemangkasan daun yang terinfeksi dan aplikasikan fungisida yang direkomendasikan secara tepat waktu. Pastikan untuk melakukan penyiraman pada pagi hari agar tanah dapat mengering sebelum malam.', 'Melakukan rotasi tanaman dengan tanaman lain yang tidak berhubungan dengan kentang untuk mencegah infeksi. Tanam varietas kentang yang lebih tahan terhadap penyakit ini, dan pastikan tanah memiliki drainase yang baik untuk menghindari kelembaban berlebih.'),
('disease_22', 'plant_19', 'Potato Late Blight', 'Potato Late Blight adalah penyakit yang lebih serius, ditandai dengan bercak-bercak hitam pada daun dan batang, serta pembusukan pada umbi. Ini dapat menyebabkan kerugian besar dalam hasil panen.', 'Jamur Phytophthora infestans, yang berkembang biak dalam kondisi lembab dan suhu dingin.', 'Untuk mengatasi tanaman yang terinfeksi, penting untuk segera menghilangkan bagian yang terinfeksi dan menerapkan fungisida secara rutin. Penggunaan varietas kentang yang tahan terhadap late blight juga sangat disarankan.', NULL),
('disease_23', 'plant_19', 'Healthy Potato', 'Tanaman kentang yang sehat menunjukkan pertumbuhan yang baik dengan daun hijau cerah yang lebat dan tegak. Daun tidak menunjukkan tanda-tanda kerusakan atau penyakit, dan umbi kentang tumbuh dengan baik di dalam tanah. Pertumbuhan akar juga optimal, memastikan tanaman dapat menyerap air dan nutrisi yang diperlukan untuk perkembangan yang sehat.', NULL, 'Penyiraman harus dilakukan secara teratur, dengan memastikan tanah selalu lembab, terutama selama fase pertumbuhan umbi, tetapi hindari penyiraman berlebihan. Lakukan pemantauan rutin terhadap hama seperti kumbang kentang dan ulat, serta gunakan insektisida sesuai kebutuhan. Pemberian pupuk seimbang yang kaya akan nitrogen untuk mendukung pertumbuhan vegetatif dan kalium untuk pertumbuhan umbi juga dianjurkan. Pastikan jarak tanam yang cukup untuk meningkatkan sirkulasi udara dan mengurangi risiko penyakit.', NULL),
('disease_24', 'plant_20', 'Healthy Raspberry', 'Tanaman raspberry yang sehat memiliki batang yang kuat dan tegak, serta daun hijau yang lebar dan segar. Tanaman ini tumbuh subur dengan cabang-cabang yang rimbun, dan tidak menunjukkan tanda-tanda infeksi atau kerusakan. Buah raspberry biasanya tumbuh dalam kelompok, berwarna merah cerah, manis, dan beraroma segar, dengan kualitas tinggi.', NULL, 'Pastikan tanaman mendapatkan penyiraman yang cukup, terutama selama periode pembentukan buah. Berikan pupuk yang kaya nitrogen di awal musim tanam dan pupuk yang lebih kaya kalium dan fosfor saat tanaman mulai berbuah. Pemangkasan pasca panen diperlukan untuk meningkatkan produksi buah di tahun berikutnya dan menjaga bentuk tanaman. Selain itu, lakukan pemantauan untuk hama seperti kutu daun dan buah raspberry, dan gunakan pestisida organik jika diperlukan.', NULL),
('disease_25', NULL, 'Healthy Soybean', 'Tanaman kedelai yang sehat menunjukkan pertumbuhan yang baik dengan daun hijau segar yang lebar dan berkilau. Daun tidak memiliki bercak atau kerusakan, dan tanaman tumbuh tegak dengan cabang yang rimbun. Tanaman kedelai juga memiliki akar yang berkembang dengan baik, membantu penyerapan air dan nutrisi secara optimal.', NULL, 'Pastikan tanaman mendapatkan penyiraman yang cukup, terutama pada fase awal pertumbuhan dan saat pembentukan polong. Gunakan pupuk yang kaya akan nitrogen, fosfor, dan kalium untuk mendukung pertumbuhan tanaman secara keseluruhan. Lakukan pemantauan untuk hama seperti penggerek batang dan kutu, dan terapkan metode pengendalian yang sesuai. Selain itu, terapkan rotasi tanaman untuk mengurangi risiko serangan penyakit dan meningkatkan kesehatan tanah.', NULL),
('disease_26', NULL, 'Squash Powdery Mildew', 'Squash Powdery Mildew adalah penyakit yang ditandai dengan lapisan putih seperti bubuk pada daun, yang dapat mengurangi fotosintesis dan kualitas buah.', 'Jamur Podosphaera xanthii, yang berkembang baik pada kondisi panas dan kering.', 'Merawat tanaman yang terinfeksi meliputi menghilangkan daun yang terinfeksi dan menggunakan fungisida untuk mengendalikan pertumbuhan jamur. Menerapkan praktik pengelolaan tanaman yang baik, seperti menanam varietas squash yang tahan, dapat membantu.', 'Pencegahan dapat dilakukan dengan menjaga jarak antar tanaman untuk meningkatkan sirkulasi udara, menghindari penyiraman berlebih pada daun, dan melakukan rotasi tanaman untuk mencegah penumpukan patogen di tanah.'),
('disease_27', NULL, 'Strawberry Leaf Scorch', 'Strawberry Leaf Scorch adalah penyakit yang menyerang tanaman stroberi, yang ditandai dengan munculnya bercak-bercak kuning pada daun yang akhirnya menyebabkan layu dan kematian daun. Penyakit ini dapat mengakibatkan penurunan hasil buah dan kualitas tanaman secara keseluruhan. Gejala awal sering kali muncul pada daun yang lebih tua dan dapat menyebar ke seluruh tanaman jika tidak ditangani dengan tepat.', 'Strawberry Leaf Scorch disebabkan oleh infeksi virus, terutama oleh Strawberry mottle virus (SMoV) dan Strawberry vein banding virus (SVBV). Virus ini menyebar melalui serangga penghisap, seperti kutu daun, serta melalui peralatan pertanian yang terkontaminasi. Kondisi lingkungan yang lembap dan suhu tinggi juga dapat memperparah penyebaran penyakit ini.', 'Untuk mengatasi infeksi, penting untuk menghilangkan tanaman yang terinfeksi dan memastikan tanaman mendapatkan cukup air serta nutrisi. Pengendalian hama, terutama kutu daun, juga sangat dianjurkan dengan penggunaan pestisida yang sesuai.', 'Untuk mencegah penyakit ini, pilih varietas stroberi yang tahan terhadap virus, jaga kebersihan kebun, dan lakukan rotasi tanaman. Memastikan sirkulasi udara yang baik di sekitar tanaman juga penting untuk mencegah perkembangan penyakit.'),
('disease_28', NULL, 'Healthy Strawberry', 'Strawberry yang sehat ditandai dengan daun yang hijau cerah, batang yang kokoh, dan buah yang padat serta berwarna cerah. Tanaman ini memerlukan kondisi tanah yang baik, cukup sinar matahari, dan kelembapan yang tepat untuk tumbuh dengan optimal. Tanaman strawberry juga sensitif terhadap hama dan penyakit, sehingga penting untuk menjaga kesehatan mereka melalui praktik perawatan yang baik.', NULL, 'Untuk merawat strawberry agar tetap sehat, penting untuk memastikan bahwa tanaman mendapatkan cukup air tanpa tergenang, menggunakan pupuk seimbang yang mengandung nitrogen, fosfor, dan kalium, serta melakukan pemeriksaan rutin untuk mendeteksi hama dan penyakit. Selain itu, pemangkasan daun yang terinfeksi atau mati dapat membantu mencegah penyebaran penyakit. Dengan perawatan yang baik, strawberry dapat tumbuh subur dan menghasilkan buah dengan baik.', NULL),
('disease_29', 'plant_22', 'Tomato Bacterial Spot', 'Tomato Bacterial Spot adalah penyakit yang disebabkan oleh bakteri Xanthomonas campestris yang menyerang tanaman tomat. Gejala awalnya ditandai dengan munculnya bercak air pada daun, yang kemudian berkembang menjadi bercak kuning dan akhirnya mengering. Penyakit ini dapat menyebabkan penurunan hasil panen yang signifikan.', 'Penyakit ini menyebar melalui air, tanah, dan kontak langsung antara tanaman yang terinfeksi dengan yang sehat. Kondisi lingkungan yang lembab dan hangat mendukung perkembangan bakteri ini, menjadikannya lebih umum di daerah dengan iklim tersebut.', 'Untuk mengatasi infeksi, penting untuk menghilangkan dan menghancurkan bagian tanaman yang terinfeksi. Menggunakan varietas tomat yang tahan terhadap penyakit ini juga sangat dianjurkan. Selain itu, menjaga kelembaban tanah dan memperbaiki drainase dapat membantu mengurangi penyebaran penyakit.', 'Pencegahan dapat dilakukan dengan melakukan rotasi tanaman, memastikan jarak tanam yang cukup agar sirkulasi udara baik, serta membersihkan alat pertanian sebelum dan setelah digunakan. Penggunaan mulsa juga dapat membantu mengurangi kontak tanah dengan daun.'),
('disease_30', 'plant_22', 'Tomato Early Blight', 'Tomato Early Blight adalah penyakit yang disebabkan oleh jamur Alternaria solani, yang menyerang tanaman tomat pada semua tahap pertumbuhan. Gejala awal muncul sebagai bercak kecoklatan pada daun yang dapat berkembang menjadi bercak yang lebih besar, mengering, dan menyebabkan daun mati. Jika tidak ditangani, penyakit ini dapat menurunkan hasil panen dan kualitas buah.', 'Jamur ini menyebar melalui spora yang dapat terbang melalui angin dan hujan. Kelembaban yang tinggi dan suhu hangat menciptakan kondisi ideal bagi jamur ini untuk berkembang. Tanaman yang lemah karena stres, seperti kekurangan nutrisi atau air, lebih rentan terhadap infeksi.', 'Menghilangkan bagian tanaman yang terinfeksi segera setelah gejala terlihat sangat penting untuk mencegah penyebaran. Menggunakan fungisida yang tepat juga dianjurkan untuk mengendalikan infeksi. Pastikan untuk mengikuti instruksi label untuk aplikasi yang efektif.', 'Pencegahan bisa dilakukan dengan memilih varietas tomat yang tahan terhadap Early Blight dan mengatur jarak tanam agar sirkulasi udara optimal. Mengatur sistem irigasi untuk mencegah kelembaban berlebih dan melakukan rotasi tanaman juga sangat membantu. Selain itu, membersihkan alat pertanian dan sampah tanaman setelah panen akan mengurangi sumber infeksi.'),
('disease_31', 'plant_22', 'Tomato Late Blight', 'Tomato Late Blight adalah penyakit serius yang disebabkan oleh jamur Phytophthora infestans, yang dapat menyebabkan kerusakan besar pada tanaman tomat dan kentang. Gejala awal muncul sebagai bercak minyak berwarna hijau muda pada daun, yang kemudian berkembang menjadi bercak coklat gelap yang cepat menyebar.', 'Phytophthora infestans, yang menyebar melalui spora yang terbawa angin, air, atau alat pertanian yang terkontaminasi. Penyebaran paling sering terjadi pada kondisi lembab dan suhu dingin.', 'Penggunaan fungisida berbasis metalaksil dapat membantu mengendalikan penyakit ini. Tanaman yang terinfeksi harus segera dihancurkan untuk mencegah penyebaran lebih lanjut. Penyiraman pada akar tanaman dan menghindari kontak air dengan daun dapat membantu mengurangi perkembangan jamur.', 'Pencegahan dapat dilakukan dengan memilih varietas tomat yang tahan terhadap penyakit ini dan memastikan jarak tanam yang cukup agar tanaman memiliki sirkulasi udara yang baik. Selain itu, melakukan rotasi tanaman dan membersihkan alat pertanian sangat dianjurkan.'),
('disease_32', 'plant_22', 'Tomato Leaf Mold', 'Tomato Leaf Mold adalah penyakit yang disebabkan oleh jamur Cladosporium fulvum. Penyakit ini biasanya muncul pada daun tomat, terutama pada bagian bawahnya. Gejala awal meliputi bercak kuning yang kemudian berkembang menjadi bercak hijau zaitun yang dapat terlihat berbulu. Jika tidak diobati, penyakit ini dapat menyebabkan daun mati, mengurangi fotosintesis, dan akhirnya mempengaruhi hasil panen.', 'Jamur ini berkembang biak dalam kondisi lembab dan suhu yang hangat, biasanya antara 20-25°C. Penyebarannya terjadi melalui spora yang dapat dibawa oleh angin dan air. Keberadaan kelembapan yang tinggi dan sirkulasi udara yang buruk di sekitar tanaman dapat meningkatkan risiko infeksi.', 'Penanganan terhadap Tomato Leaf Mold melibatkan pemangkasan daun yang terinfeksi dan penggunaan fungisida berbasis copper atau azoxystrobin. Pemberian fungisida harus dilakukan secara rutin, terutama saat kondisi lingkungan mendukung pertumbuhan jamur.', 'Untuk mencegah penyakit ini, penting untuk memilih varietas tomat yang tahan terhadap Leaf Mold. Menjaga jarak tanam yang cukup untuk sirkulasi udara yang baik dan menghindari penyiraman dari atas dapat membantu mencegah infeksi. Praktik rotasi tanaman dan membersihkan area sekitar tanaman dari sisa-sisa tanaman sebelumnya juga dianjurkan.'),
('disease_33', 'plant_22', 'Tomato Septoria Leaf Spot', 'Tomato Septoria Leaf Spot adalah penyakit yang disebabkan oleh jamur Septoria lycopersici. Gejala awal ditandai dengan munculnya bercak bulat kecil berwarna coklat gelap atau hitam pada daun, yang sering kali dikelilingi oleh halo kuning. Penyakit ini dapat menyebabkan daun menjadi kuning dan jatuh, sehingga mempengaruhi pertumbuhan dan hasil buah tomat.', 'Jamur ini menyebar melalui spora yang terbawa oleh air, angin, dan peralatan pertanian. Kondisi lembab dan suhu yang hangat merupakan faktor yang mendukung perkembangan penyakit ini. Daun yang basah atau kelembapan tinggi di area pertumbuhan tomat dapat meningkatkan risiko infeksi.', 'Untuk mengatasi Septoria Leaf Spot, penting untuk memangkas dan membuang daun yang terinfeksi. Penggunaan fungisida berbasis copper atau mancozeb dapat membantu mengendalikan penyebaran penyakit. Selain itu, menghindari penyiraman dari atas dan menjaga kebersihan area pertanian sangat dianjurkan.', 'Mencegah infeksi dapat dilakukan dengan memilih varietas tomat yang tahan terhadap Septoria. Mengatur jarak tanam yang baik untuk memastikan sirkulasi udara dan menghindari kelembapan yang berlebihan pada daun dapat membantu. Praktik rotasi tanaman juga dianjurkan untuk mengurangi kemungkinan penyebaran jamur di tahun berikutnya.'),
('disease_34', 'plant_22', 'Tomato Spider Mites Two Spotted', 'Tomato Spider Mites, khususnya Tetranychus urticae, adalah hama kecil yang dapat menyebabkan kerusakan serius pada tanaman tomat. Gejala yang umum terlihat adalah daun yang mulai menguning, bercak kecil, dan jaringan daun yang mengering, akibat penghisapan cairan oleh tungau. Jika tidak ditangani, infestasi dapat menyebabkan penurunan hasil panen dan bahkan kematian tanaman.', 'Tungau ini berkembang biak dengan cepat di lingkungan yang hangat dan kering. Mereka biasanya menyebar melalui angin, alat pertanian, atau tanaman yang terinfeksi. Kelembapan yang rendah dan suhu tinggi mempercepat pertumbuhan populasi tungau ini.', 'Untuk mengatasi infestasi tungau, penggunaan pestisida mitisida yang tepat sangat dianjurkan. Selain itu, pemantauan rutin untuk mendeteksi tanda-tanda awal infestasi bisa membantu mengontrol jumlah populasi tungau. Menggunakan air untuk menyemprotkan tanaman dapat membantu mengurangi populasi tungau secara fisik.', 'Mencegah infestasi tungau bisa dilakukan dengan menjaga kelembapan tanah yang cukup dan menghindari penyiraman dari atas yang dapat menciptakan kondisi kering. Menanam tanaman penutup atau tanaman lain yang menarik predator alami juga bisa mengurangi populasi tungau. Praktik rotasi tanaman dan menjaga kebersihan area pertanian penting untuk mencegah penyebaran.'),
('disease_35', 'plant_22', 'Tomato Target Spot', 'Tomato Target Spot adalah penyakit yang disebabkan oleh jamur Corynespora cassiicola. Penyakit ini ditandai dengan munculnya bercak-bercak bulat pada daun yang dapat berwarna cokelat, kuning, atau hitam. Bercak ini dapat membesar dan menyebabkan daun mati, yang pada akhirnya mempengaruhi kesehatan dan hasil panen tanaman tomat.', 'Penyakit ini umumnya terjadi dalam kondisi kelembapan yang tinggi dan suhu yang hangat. Spora jamur dapat menyebar melalui angin, percikan air, dan kontak dengan alat pertanian yang terinfeksi. Tanaman yang stres karena faktor lingkungan atau nutrisi juga lebih rentan terhadap serangan penyakit ini.', 'Pengendalian penyakit ini bisa dilakukan dengan menggunakan fungisida yang sesuai. Pemantauan rutin dan penghilangan bagian tanaman yang terinfeksi juga dianjurkan untuk mencegah penyebaran. Selain itu, penting untuk menjaga kebersihan area tanam dengan menghilangkan sisa-sisa tanaman yang terinfeksi.', 'Menerapkan rotasi tanaman dan memilih varietas tomat yang tahan terhadap penyakit dapat membantu mengurangi risiko infeksi. Pengelolaan kelembapan tanah dan penggunaan sistem irigasi yang tepat juga penting untuk mencegah kondisi yang mendukung pertumbuhan jamur.'),
('disease_36', 'plant_22', 'Tomato Yellow Leaf Curl Virus', 'Tomato Yellow Leaf Curl Virus (TYLCV) adalah penyakit yang disebabkan oleh virus yang menginfeksi tanaman tomat. Gejala utama penyakit ini termasuk daun yang menguning, melengkung ke atas, dan pertumbuhan tanaman yang terhambat. Infeksi dapat menyebabkan hasil panen yang berkurang secara signifikan.', 'Virus ini ditularkan terutama melalui serangan hama, seperti thrips, yang menghisap cairan dari tanaman terinfeksi dan kemudian menyebarkannya ke tanaman sehat. Kelembapan yang tinggi dan suhu hangat dapat mempercepat penyebaran virus ini.', 'Tidak ada pengobatan spesifik untuk virus ini. Langkah terbaik adalah mencegah infeksi dengan menggunakan pestisida untuk mengontrol populasi thrips. Selain itu, pemilihan varietas tomat yang tahan terhadap virus juga dianjurkan. Menghilangkan tanaman yang terinfeksi dapat membantu mengurangi sumber penyebaran.', 'Menggunakan jaring pelindung untuk mengurangi serangan hama, menjaga kebersihan lahan pertanian, dan menerapkan rotasi tanaman merupakan langkah-langkah penting untuk menghindari penyebaran TYLCV. Pemantauan secara rutin terhadap tanaman untuk mendeteksi gejala awal juga sangat dianjurkan.'),
('disease_37', 'plant_22', 'Tomato Mosaic Virus', 'Tomato Mosaic Virus (ToMV) adalah virus yang menyebabkan gejala mosaik pada daun tanaman tomat, yang ditandai dengan bercak hijau dan kuning. Gejala ini sering diikuti oleh pertumbuhan yang terhambat dan penurunan hasil panen. Infeksi virus ini dapat mengurangi kualitas dan kuantitas tomat yang dihasilkan.', 'Virus ini ditularkan melalui kontak langsung dengan tanaman yang terinfeksi dan melalui alat pertanian yang terkontaminasi. Serangga penghisap seperti kutu daun juga dapat menyebarkan virus ini dari satu tanaman ke tanaman lainnya. Kelemahan genetik dalam varietas tomat tertentu dapat meningkatkan kerentanan terhadap infeksi.', 'Tidak ada pengobatan untuk virus ini, jadi pencegahan menjadi langkah utama. Petani disarankan untuk menanam varietas tomat yang tahan terhadap ToMV, serta melakukan sanitasi alat dan menjaga kebersihan area pertanian. Pengendalian hama juga penting untuk mencegah penyebaran virus.', 'Menghindari penanaman tomat di dekat tanaman yang terinfeksi, menghapus tanaman yang menunjukkan gejala infeksi, dan mengimplementasikan rotasi tanaman dapat membantu mengurangi risiko penyebaran Tomato Mosaic Virus. Monitoring secara berkala untuk mendeteksi tanda-tanda awal infeksi juga sangat penting.'),
('disease_38', 'plant_22', 'Tomato Healthy', 'Tomato yang sehat adalah tanaman yang tumbuh dengan baik, memiliki daun hijau cerah, buah yang matang dan bebas dari gejala penyakit. Tanaman tomat sehat dapat mencapai tinggi yang optimal dan menghasilkan buah dengan ukuran, bentuk, dan warna yang sesuai dengan varietasnya. Kesehatan tanaman tomat sangat dipengaruhi oleh kondisi lingkungan, pengelolaan hama, dan praktik pertanian yang baik.', NULL, 'Pastikan tanaman tomat mendapatkan pupuk seimbang yang kaya nutrisi, lakukan penyiraman yang konsisten tanpa membuat tanah terlalu lembab, dan gunakan mulsa untuk menjaga kelembapan tanah. Pemangkasan daun yang rusak dan rotasi tanaman juga penting untuk kesehatan tanaman. Monitor hama secara rutin dan gunakan pestisida organik jika diperlukan.', NULL);

-- --------------------------------------------------------

--
-- Struktur dari tabel `plant_encyclopedia`
--

CREATE TABLE `plant_encyclopedia` (
  `plant_id` varchar(255) NOT NULL,
  `plant_name` varchar(255) NOT NULL,
  `scientific_name` varchar(255) DEFAULT NULL,
  `description` text,
  `care_tips` text,
  `harvest_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `watering_frequency` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `watering_time` time DEFAULT NULL,
  `watering_interval` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `origin_place` varchar(255) DEFAULT NULL,
  `climate` varchar(255) DEFAULT NULL,
  `fertilizer` varchar(255) DEFAULT NULL,
  `uses` text,
  `common_disease` text,
  `harvest_time_days` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data untuk tabel `plant_encyclopedia`
--

INSERT INTO `plant_encyclopedia` (`plant_id`, `plant_name`, `scientific_name`, `description`, `care_tips`, `harvest_time`, `watering_frequency`, `watering_time`, `watering_interval`, `origin_place`, `climate`, `fertilizer`, `uses`, `common_disease`, `harvest_time_days`) VALUES
('plant_00', 'Snake plant', 'Dracaena trifasciata', 'Snake Plant memiliki karakteristik daun panjang yang tumbuh tegak, berbentuk seperti pedang dengan ujung runcing. Daunnya keras, bertekstur, dan sering menampilkan pola garis-garis horizontal hijau muda atau abu-abu pada permukaan hijau tua, dengan beberapa varietas memiliki tepi berwarna kuning (variegata). Tanaman ini biasanya memiliki tinggi antara 30 cm hingga 120 cm, tergantung varietasnya, dengan lebar mencapai 20-40 cm yang dipengaruhi oleh jumlah daun. Snake Plant adalah tanaman yang tahan terhadap berbagai kondisi lingkungan, menjadikannya sangat cocok untuk dekorasi indoor maupun outdoor.', NULL, '6 bulan hingga 1 tahun untuk mencapai ukuran optimal (30-60 cm) dalam kondisi perawatan yang baik, tergantung lingkungan dan varietas.', '2 minggu sekali (musim panas), 3-4 minggu sekali (musim dingin).', NULL, 'Disiram setiap 2-3 minggu, tergantung kelembapan tanah dan suhu.', 'Afrika Barat', 'Iklim tropis dan subtropis; suhu ideal 15-30C', 'Pupuk cair atau pupuk slow-release berbasis nitrogen rendah, digunakan setiap 2-3 bulan selama musim tanam (musim semi dan panas)', 'Obat: Dalam pengobatan tradisional, digunakan untuk mengobati sakit kepala ringan dan sebagai pembersih udara alami. Hiasan: Tanaman hias yang populer untuk dekorasi rumah dan kantor karena toleransi rendah perawatan.', 'Root Rot (Busuk Akar): Penyebab: Overwatering atau tanah yang tidak memiliki drainase baik. Leaf Spot (Bercak Daun): Penyebab: Infeksi jamur atau bakteri akibat kelembapan berlebih. Mealybugs (Kutu Putih): Penyebab: Serangan hama yang mengisap getah tanaman.', NULL),
('plant_01', 'Ponytail Palm', 'Beaucarnea recurvata', 'Ponytail Palm memiliki batang tebal berbentuk seperti botol di pangkalnya, yang berfungsi menyimpan air. Daunnya panjang, melengkung, dan berbentuk seperti pita dengan ujung yang lembut, tumbuh membentuk roset menyerupai ekor kuda. Tinggi tanaman ini bervariasi, dapat mencapai 30 cm hingga 4 meter tergantung usia dan lingkungan, dengan lebar sekitar 30-60 cm. Warnanya hijau cerah, menambah kesan segar sebagai dekorasi.', NULL, '5-10 tahun tergantung kondisi pertumbuhan.', '2-4 minggu sekali (musim panas), 4-6 minggu (musim dingin).', NULL, 'Disiram setiap 2-4 minggu, tergantung kelembapan tanah.', 'Meksiko', 'Iklim hangat dan semi-kering, dengan suhu ideal 20-30C', 'Pupuk cair berbasis nitrogen rendah, diaplikasikan setiap 1-2 bulan selama musim tanam (musim semi dan panas).', 'Hiasan: Sangat populer sebagai tanaman hias, baik untuk indoor maupun outdoor, karena bentuknya yang unik dan mudah dirawat.', 'Root Rot: Disebabkan oleh overwatering. Leaf Tip Browning: Karena kekurangan air atau kelembapan rendah. Mealybugs dan Spider Mites: Hama umum yang menyerang daun.', NULL),
('plant_02', 'Polka Dot Plant', 'Hypoestes phyllostachya', 'Polka Dot Plant adalah tanaman hias berukuran kecil yang dikenal dengan pola bintik warna-warni pada daunnya. Daun berbentuk oval dengan warna dasar hijau dihiasi bintik merah muda, putih, atau merah yang mencolok. Tinggi tanaman ini sekitar 20–40 cm dengan lebar hingga 30 cm, menjadikannya tanaman dekorasi yang cantik untuk ruangan atau taman kecil.', NULL, '6-12 bulan setelah penanaman', '2-3 kali per minggu, 200 ml per penyiraman. Sesuaikan dengan kondisi tanah.', NULL, 'Disiram 2-3 kali per minggu dengan jumlah air sekitar 200 ml per penyiraman untuk tanaman berukuran 20-30 cm. Pastikan tanah tetap lembap tetapi tidak basah.', 'Madagaskar', 'Iklim Tropis dengan kelembapan tinggi, suhu ideal 18-30C', 'Pupuk cair organik rendah nitrogen, diaplikasikan setiap 2 minggu selama musim tanam.', 'Hiasan: Polka Dot Plant sangat cocok sebagai tanaman meja atau penghias taman kecil karena pola warna-warni daunnya.', 'Powdery Mildew: Infeksi jamur akibat kelembapan tinggi, menyebabkan lapisan putih pada daun. Aphids: Hama kecil yang menyerang daun muda, membuatnya keriting. Root Rot: Disebabkan oleh penyiraman berlebih sehingga akar membusuk.', NULL),
('plant_03', 'Monstera Deliciosa', 'Monstera Deliciosa', 'Monstera Deliciosa, juga dikenal sebagai \"Tanaman Keju Swiss,\" memiliki daun besar dengan lubang atau belahan khas yang memberikan tampilan tropis yang elegan. Daunnya berwarna hijau tua dan dapat mencapai ukuran 90 cm. Tanaman ini tumbuh hingga 3 meter di dalam ruangan jika diberi penyangga seperti tiang lumut. Selain keindahannya, Monstera juga dikenal sebagai tanaman pembersih udara alami.', NULL, '12 bulan untuk matang dan menghasilkan buah yang dapat dimakan.', '1 minggu sekali di musim panas dan 2 minggu sekali di musim dingin, dengan air secukupnya untuk membasahi seluruh tanah.', NULL, 'Disiram seminggu sekali dengan jumlah air yang cukup untuk membuat seluruh media tanam basah hingga ke dasar pot.', 'Amerika Tengah', 'Iklim tropis dengan suhu 20-30C dan kelembapan tinggi', 'Pupuk cair NPK, diaplikasikan sebulan sekali selama musim tanam (musim semi dan panas).', 'Hiasan: Monstera sangat populer sebagai tanaman indoor karena estetika tropisnya.', 'Root Rot: Disebabkan oleh drainase buruk atau penyiraman berlebih. Spider Mites: Hama kecil yang menyerang bagian bawah daun, menyebabkan bercak kuning. Leaf Spot: Infeksi jamur yang menyebabkan bercak coklat pada daun.', NULL),
('plant_04', 'Elephant Ear', 'Alocasia spp.', 'Elephant Ear adalah tanaman hias tropis dengan daun besar berbentuk hati yang menyerupai telinga gajah, sehingga menjadi pusat perhatian di taman atau ruangan. Daunnya biasanya berwarna hijau tua dengan tekstur yang halus atau sedikit bergelombang, dan beberapa varietas memiliki garis-garis kontras yang mencolok. Tanaman ini dapat mencapai tinggi 1–2 meter dengan lebar hingga 1 meter, tergantung spesiesnya.', NULL, '6–12 bulan untuk menghasilkan umbi yang dapat dimakan', '3–4 kali per minggu di musim panas dan 1–2 kali per minggu di musim dingin, dengan jumlah air yang cukup untuk menjaga kelembapan tanah.', NULL, 'Disiram 3–4 kali per minggu untuk menjaga tanah tetap lembap, terutama selama musim panas. Selama musim dingin, cukup 1–2 kali per minggu.', 'Asia Tenggara', 'Iklim tropis dan subtropis dengan suhu ideal 21–32C dan kelembapan tinggi.', 'Pupuk cair dengan kandungan nitrogen tinggi, diaplikasikan setiap 2 minggu selama musim tanam.', 'Hiasan: Daunnya yang besar dan unik menjadikannya tanaman hias favorit untuk area taman tropis atau ruang terbuka. Bahan makanan: Umbi dari beberapa spesies dapat diolah menjadi makanan tradisional.', 'Root Rot: Disebabkan oleh penyiraman berlebih atau drainase buruk. Spider Mites: Hama kecil yang menyerang bagian bawah daun, meninggalkan bercak kuning. Leaf Spot: Infeksi jamur yang menyebabkan bercak coklat pada daun.', NULL),
('plant_05', 'Dumb Cane', 'Dieffenbachia spp.', 'Dumb Cane adalah tanaman berdaun besar dengan pola unik berupa bercak putih, hijau muda, atau krem di daunnya. Tanaman ini biasanya tumbuh hingga setinggi 1-2 meter sebagai tanaman indoor. Lebar daun bisa mencapai 20-30 cm. Tumbuhan ini dikenal karena kemampuannya menyaring udara, tetapi getahnya beracun dan dapat menyebabkan iritasi jika tersentuh atau tertelan.', NULL, '60-90 hari untuk mencapai ukuran yang cukup besar dan menarik sebagai tanaman hias setelah ditanam dari stek atau bibit.', '7-10 hari sekali, tergantung pada kelembaban lingkungan dan musim.', NULL, 'Disiram ketika lapisan atas tanah mulai kering. Terlalu banyak air dapat menyebabkan busuk akar.', 'Amerika Tengah dan Selatan', 'Iklim tropis dan subtropis dengan suhu antara 18-24C', 'Pupuk cair serbaguna setiap 4-6 minggu selama musim tumbuh (musim semi dan musim panas).', 'Hiasan: Sangat populer sebagai tanaman dekorasi indoor karena perawatannya yang mudah dan penampilannya yang menarik.', 'Leaf spot: Disebabkan oleh infeksi jamur atau bakteri. Root rot: Akibat penyiraman berlebih atau drainase buruk. Pest infestations: Rentan terhadap kutu daun, tungau laba-laba, dan serangga skala.', NULL),
('plant_06', 'Dracaena', 'Dracaena spp.', 'Dracaena adalah tanaman hias dengan daun yang panjang, ramping, dan sering bergaris atau berwarna hijau tua dengan variasi putih, kuning, atau merah. Batangnya keras dan tegak, menyerupai batang pohon kecil. Tanaman ini tumbuh lambat dan bisa mencapai tinggi hingga 2-3 meter di dalam ruangan, dengan lebar sekitar 50-100 cm. Dracaena dikenal sebagai tanaman yang mudah dirawat dan mampu menyaring udara di dalam ruangan.', NULL, '90-120 hari diperlukan untuk mencapai ukuran cukup besar.', 'Setiap 7-14 hari tergantung kelembapan dan suhu.', NULL, 'Disiram setiap 1-2 minggu, pastikan air tidak tergenang di pot.', 'Afrika, Asia, dan Amerika Tengah', 'Iklim tropis dan subtropis dengan suhu antara 18-24C', 'Pupuk cair serbaguna atau pupuk khusus tanaman hias setiap 4-6 minggu selama musim semi dan musim panas.', 'Hiasan: Sangat populer sebagai tanaman dekorasi indoor karena perawatannya yang mudah dan penampilannya yang elegan.', 'Leaf spot: Disebabkan oleh infeksi jamur atau bakteri. Root rot: Akibat penyiraman berlebih atau drainase buruk. Brown tips: Disebabkan oleh kekurangan kelembaban atau air dengan kandungan fluoride tinggi.', NULL),
('plant_08', 'Birds Nest Fern', 'Asplenium nidus', 'Bird\'s Nest Fern adalah tanaman paku yang memiliki daun panjang, lebar, berwarna hijau terang dengan tekstur mengkilap. Daunnya tumbuh melingkar dari pusat seperti sarang burung, itulah asal namanya. Tanaman ini dapat tumbuh setinggi 60-120 cm dengan lebar 50-100 cm. Tanaman ini sangat estetis dan populer sebagai dekorasi karena keindahan daunnya yang unik dan mudah dirawat.', NULL, '90-120 hari untuk mencapai ukuran yang menarik sebagai dekorasi.', '7-14 hari, tergantung pada kelembaban tanah dan lingkungan.', NULL, 'Disiram ketika tanah mulai kering, tetapi jangan biarkan tanah terlalu kering. Frekuensi penyiraman biasanya setiap 1-2 minggu tergantung pada kelembaban lingkungan.', 'Asia Tenggara, Afrika, dan Australia', 'Iklim tropis dan subtropis dengan suhu ideal antara 18-27C. Membutuhkan kelembaban tinggi.', 'Pupuk cair untuk tanaman hijau atau tanaman hias setiap 6-8 minggu selama musim tumbuh.', 'Hiasan: Sering digunakan sebagai tanaman dekorasi indoor atau outdoor karena penampilannya yang estetis dan kemampuannya menambah kesan tropis.', 'Leaf spot: Disebabkan oleh infeksi jamur atau bakteri. Brown tips: Disebabkan oleh udara kering atau air dengan kandungan garam atau mineral tinggi. Pest infestations: Rentan terhadap tungau laba-laba dan kutu putih.', NULL),
('plant_09', 'Areca Palm', 'Dypsis lutescens', 'Areca Palm adalah tanaman hias dengan batang ramping menyerupai buluh dan daun panjang berbentuk melengkung yang terdiri dari banyak daun kecil berwarna hijau terang. Tumbuhan ini biasanya tumbuh setinggi 1,5–3 meter dalam ruangan dan bisa mencapai 6–12 meter di luar ruangan. Areca Palm sering digunakan untuk menciptakan nuansa tropis di rumah dan dikenal sebagai salah satu tanaman pembersih udara alami.', NULL, '90-180 hari sejak ditanam, tergantung pada kondisi perawatan.', '7-14 hari, tergantung pada kelembaban tanah dan lingkungan.', NULL, 'Disiram secara teratur, memastikan tanah tetap lembab tetapi tidak basah. Penyiraman biasanya diperlukan 1-2 kali seminggu, tergantung pada kelembaban lingkungan.', 'Madagaskar', 'Iklim tropis dan subtropis dengan suhu ideal antara 18-30C. Areca Palm membutuhkan kelembaban tinggi.', 'Pupuk khusus tanaman tropis atau pupuk cair serbaguna setiap 6-8 minggu selama musim semi dan musim panas.', 'Hiasan: Sering digunakan sebagai tanaman dekorasi indoor dan outdoor karena penampilannya yang tropis dan kemampuannya menyaring udara.', 'Leaf spot: Disebabkan oleh jamur atau bakteri. Root rot: Akibat penyiraman berlebihan atau drainase buruk. Brown tips: Disebabkan oleh kekurangan kelembaban atau air dengan kandungan fluoride atau klorin tinggi.', NULL),
('plant_10', 'Aloe Vera', 'Aloe barbadensis miller', 'Aloe Vera adalah tanaman sukulen dengan daun tebal berwarna hijau kebiruan, berbentuk segitiga, dan ujungnya berduri kecil. Tanaman ini dikenal karena getahnya yang kaya manfaat untuk kesehatan dan kecantikan. Tingginya dapat mencapai 30–60 cm, sementara lebarnya bervariasi tergantung kondisi pertumbuhan. Aloe Vera adalah tanaman perawatan rendah yang tumbuh baik di dalam maupun di luar ruangan.', NULL, '6-8 bulan sejak ditanam untuk gelnya.', '7–14 hari, tergantung pada kelembaban tanah dan suhu lingkungan.', NULL, 'Disiram biasanya 1-2 minggu sekali, tergantung kondisi cuaca.', 'Afrika Utara dan Timur Tengah', 'Iklim kering hingga semi-tropis dengan suhu antara 20–30C', 'Pupuk organik atau pupuk sukulen sekali setiap bulan selama musim semi dan musim panas.', 'Hiasan: Cocok untuk dekorasi indoor dan outdoor karena bentuknya yang unik. Obat: Digunakan sebagai bahan alami untuk perawatan kulit, luka bakar ringan, dan masalah pencernaan. Bahan makanan: Gel Aloe Vera sering dijadikan bahan untuk minuman atau makanan kesehatan.', 'Root rot: Disebabkan oleh penyiraman berlebih. Pest infestations: Rentan terhadap kutu putih dan tungau laba-laba. Soft rot: Akibat infeksi bakteri atau jamur.', 180),
('plant_11', 'Peach', 'Prunus persica', 'Peach adalah tanaman buah yang memiliki pohon kecil hingga sedang dengan daun hijau lonjong dan bunga berwarna merah muda atau putih. Buah persiknya berbentuk bulat dengan kulit berbulu halus, daging buah manis yang lembut, dan biji keras di bagian tengah. Tinggi pohonnya dapat mencapai 3-8 meter, dengan diameter tajuk sekitar 3-5 meter.', NULL, '90-150 hari setelah berbunga.', '1-2 kali seminggu, tergantung pada tingkat kelembaban tanah dan kondisi cuaca.', NULL, 'Disiram secara teratur, terutama selama masa pertumbuhan dan pembentukan buah. Tanah harus tetap lembab tetapi tidak tergenang air.', 'China', 'Suhu optimal antara 18-30C', 'Gunakan pupuk kaya nitrogen, fosfor, dan kalium. Pemupukan dilakukan setiap musim semi dan musim panas.', 'Hiasan: Bunga Peach yang cantik sering digunakan sebagai tanaman hias, terutama di musim semi. Obat: Buahnya kaya akan vitamin dan antioksidan yang baik untuk kesehatan. Bahan makanan: Dikonsumsi segar atau diolah menjadi makanan seperti pai, selai, atau jus.', 'Peach leaf curl: Disebabkan oleh jamur Taphrina deformans. Brown rot: Akibat infeksi jamur pada buah matang. Powdery mildew: Lapisan putih pada daun dan batang akibat infeksi jamur.', 730),
('plant_12', 'Grape', 'Vitis vinifera', 'Anggur adalah tanaman merambat dengan batang berkayu, daun berbentuk menjari, dan buah yang tumbuh dalam tandan. Buahnya kecil, bulat atau oval, dan tersedia dalam berbagai warna seperti hijau, merah, dan ungu. Tanaman ini dapat tumbuh hingga 10-15 meter jika tidak dipangkas, tetapi biasanya dipangkas untuk mempermudah perawatan dan panen.', NULL, '150-180 hari setelah bunga mekar.', '1-2 kali seminggu, tergantung pada kelembaban tanah dan iklim.', NULL, 'Disiram secara teratur, selama masa pertumbuhan awal dan pembentukan buah. Tanah harus tetap lembab tetapi tidak tergenang air.', 'Eropa dan Asia Barat', 'Suhu optimal antara 15-30C', 'Pupuk kaya fosfor dan kalium untuk mendukung pertumbuhan buah. Pemupukan dilakukan secara rutin selama musim tumbuh.', 'Hiasan: Tanaman anggur juga dapat digunakan untuk dekorasi di pergola atau dinding taman. Obat: Kaya akan antioksidan dan vitamin, anggur memiliki manfaat kesehatan seperti meningkatkan imunitas dan melindungi jantung. Bahan makanan: Digunakan untuk konsumsi langsung, jus, kismis, atau wine.', 'Powdery mildew: Jamur yang menyebabkan lapisan putih pada daun dan buah. Downy mildew: Infeksi jamur yang menyebabkan bintik kuning pada daun. Black rot: Jamur yang menyerang buah dan daun.', 730),
('plant_18', 'Blueberry', 'Vaccinium corymbosum', 'Blueberry adalah tanaman perdu kecil dengan tinggi sekitar 1–2 meter. Daunnya kecil, oval, berwarna hijau, dan akan berubah menjadi merah keunguan pada musim gugur. Buahnya kecil, bulat, dengan diameter sekitar 0,5–1,5 cm, berwarna biru tua hingga ungu dengan lapisan lilin yang memberikan tampilan buram.', NULL, '2–3 tahun setelah tanam dari bibit.', '2–3 kali per minggu dengan jumlah air sekitar 300–500 ml per penyiraman.', NULL, 'Disiram 2–3 kali per minggu dengan jumlah air sekitar 300–500 ml per penyiraman. Pastikan tanah tetap lembap tetapi tidak tergenang air.', 'Amerika Utara', 'Iklim subtropis hingga sedang dengan suhu ideal 15–25C.', 'Pupuk asam, seperti sulfur atau NPK dengan kandungan nitrogen tinggi, diaplikasikan setiap 4–6 minggu.', 'Bahan makanan: Kaya antioksidan dan digunakan dalam kue, jus, atau smoothies.', 'Mummy Berry: Disebabkan oleh jamur Monilinia vaccinii-corymbosi. Stem Blight: Akibat infeksi Botryosphaeria dothidea. Root Rot: Disebabkan oleh jamur Phytophthora.', 700),
('plant_19', 'Potato', 'Solanum tuberosum', 'Potato atau kentang adalah tanaman berdaun hijau berbentuk oval dengan bunga kecil berwarna putih hingga ungu. Umbi kentang tumbuh di bawah tanah, berbentuk bulat hingga oval dengan kulit halus atau kasar berwarna coklat, kuning, merah, atau ungu tergantung varietas. Tanaman ini tumbuh hingga tinggi 50–100 cm.', NULL, '70–120 hari setelah tanam tergantung varietas.', '2–3 kali per minggu dengan jumlah air sekitar 1 liter per penyiraman.', NULL, 'Disiram 2–3 kali per minggu dengan jumlah air sekitar 1 liter per penyiraman. Pastikan tanah tetap lembap tetapi tidak tergenang air, terutama saat umbi mulai terbentuk.', 'Pegunungan Andes, Amerika Selatan', 'Iklim tropis hingga sedang dengan suhu ideal 15–20C.', 'Pupuk organik atau NPK dengan kandungan kalium tinggi diaplikasikan setiap 2–3 minggu.', 'Bahan makanan: Sumber utama karbohidrat di banyak negara. Industri: Digunakan dalam produksi tepung kentang dan makanan olahan.', 'Late Blight: Disebabkan oleh jamur Phytophthora infestans. Blackleg: Akibat infeksi bakteri Pectobacterium atrosepticum. Common Scab: Disebabkan oleh bakteri Streptomyces scabies.', 80),
('plant_20', 'Raspberry', 'Rubus idaeus', 'Raspberry adalah tanaman perdu kecil dengan cabang yang berduri dan daun majemuk berbentuk oval bergerigi. Tanaman ini menghasilkan buah kecil yang terdiri dari banyak druplet, berwarna merah cerah, kuning, ungu, atau hitam, tergantung varietas. Buahnya memiliki tekstur lembut dengan rasa manis dan sedikit asam. Tinggi tanaman bisa mencapai 1,5–2 meter, dengan lebar sekitar 1 meter. Raspberry juga sering berbunga putih kecil yang mempercantik tanaman saat musim semi.', NULL, '1–2 tahun setelah tanam.', '2–3 kali per minggu dengan jumlah air sekitar 500 ml per penyiraman.', NULL, 'Disiram 2–3 kali per minggu dengan jumlah air sekitar 500 ml per penyiraman. Pastikan tanah tetap lembap terutama saat musim panas atau saat buah mulai matang.', 'Eropa dan Asia Utara', 'Iklim subtropis hingga sedang, dengan suhu ideal 16–25C.', 'Pupuk organik kaya nitrogen atau pupuk NPK seimbang diaplikasikan setiap bulan selama musim tanam.', 'Bahan makanan: Dimakan segar, dijadikan jus, selai, atau bahan kue. Kesehatan: Kaya akan vitamin C dan antioksidan, membantu meningkatkan sistem imun.', 'Raspberry Cane Blight: Disebabkan oleh jamur Leptosphaeria coniothyrium. Root Rot: Akibat jamur Phytophthora fragariae. Powdery Mildew: Infeksi jamur yang menyebabkan lapisan putih pada daun.', 730),
('plant_21', 'Apple', 'Malus domestica', 'Apple atau apel adalah pohon buah yang berukuran sedang dengan daun hijau berbentuk oval bergigi halus. Bunganya kecil berwarna putih dengan semburat merah muda, tumbuh berkelompok. Buah apel berbentuk bulat dengan kulit halus, tersedia dalam berbagai warna seperti merah, hijau, atau kuning, tergantung varietas. Apel memiliki daging buah yang renyah dengan rasa manis hingga asam. Tinggi pohon apel berkisar antara 4–10 meter, dengan lebar mahkota sekitar 3–6 meter. Tanaman ini dikenal karena masa tanam yang panjang dan kemampuan adaptasinya yang baik.', NULL, '3–5 tahun setelah tanam dari bibit.', '2–3 kali per minggu dengan jumlah air sekitar 3–5 liter per penyiraman.', NULL, 'Disiram 2–3 kali per minggu dengan jumlah air sekitar 3–5 liter per penyiraman untuk pohon dewasa. Tanah harus lembap tetapi tidak terlalu basah.', 'Asia', 'Iklim subtropis hingga sedang, dengan suhu ideal 18–24C.', 'Pupuk organik atau NPK dengan kandungan kalium tinggi diaplikasikan setiap bulan selama musim tanam.', 'Bahan makanan: Dikonsumsi langsung atau digunakan dalam pembuatan jus, pai, dan saus. Kesehatan: Kaya akan serat dan vitamin C, baik untuk pencernaan dan kesehatan kulit.', 'Apple Scab: Disebabkan oleh jamur Venturia inaequalis. Fire Blight: Infeksi bakteri Erwinia amylovora. Powdery Mildew: Infeksi jamur pada daun dan bunga.', 1300),
('plant_22', 'Tomato', 'Solanum lycopersicum', 'Tomato atau tomat adalah tanaman semak dengan daun majemuk berbentuk oval dan bergerigi. Tanaman ini menghasilkan buah kecil hingga sedang berbentuk bulat atau lonjong, tersedia dalam warna merah, kuning, hijau, dan oranye. Tomat memiliki daging buah yang berair dengan rasa segar dan manis sedikit asam. Tinggi tanaman tomat berkisar antara 60 cm hingga 2 meter, tergantung varietas dan teknik perawatan. Bunganya kecil, berwarna kuning cerah, tumbuh dalam kelompok.', NULL, '60–80 hari setelah tanam dari bibit.', '2–3 kali per minggu dengan jumlah air sekitar 1 liter per penyiraman.', NULL, 'Disiram 2–3 kali per minggu dengan jumlah air sekitar 1 liter per penyiraman untuk tanaman berukuran 30–50 cm. Hindari penyiraman langsung pada daun untuk mencegah penyakit.', 'Amerika Selatan', 'Iklim tropis hingga sedang, dengan suhu ideal 20–30C.', 'Pupuk organik atau NPK dengan kandungan fosfor dan kalium tinggi diaplikasikan setiap 2–3 minggu.', 'Bahan makanan: Digunakan dalam salad, saus, sup, dan jus. Kesehatan: Kaya akan likopen, antioksidan yang baik untuk kesehatan jantung dan kulit.', 'Blossom End Rot: Disebabkan oleh kekurangan kalsium. Early Blight: Akibat jamur Alternaria solani. Powdery Mildew: Infeksi jamur pada daun.', 65);

-- --------------------------------------------------------

--
-- Struktur dari tabel `prediction_result`
--

CREATE TABLE `prediction_result` (
  `prediction_id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `disease_id` varchar(255) NOT NULL,
  `uploaded_image` varchar(255) DEFAULT NULL,
  `description` text,
  `accuracy` decimal(5,2) DEFAULT NULL,
  `predicted_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Struktur dari tabel `user`
--

CREATE TABLE `user` (
  `user_id` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(50) NOT NULL,
  `no_telp` varchar(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `garden_plants`
--
ALTER TABLE `garden_plants`
  ADD PRIMARY KEY (`garden_plant_id`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `plant_id` (`plant_id`);

--
-- Indeks untuk tabel `image`
--
ALTER TABLE `image`
  ADD PRIMARY KEY (`image_id`),
  ADD KEY `plant_id` (`plant_id`);

--
-- Indeks untuk tabel `plant_diseases`
--
ALTER TABLE `plant_diseases`
  ADD PRIMARY KEY (`disease_id`),
  ADD KEY `plant_id` (`plant_id`);

--
-- Indeks untuk tabel `plant_encyclopedia`
--
ALTER TABLE `plant_encyclopedia`
  ADD PRIMARY KEY (`plant_id`);

--
-- Indeks untuk tabel `prediction_result`
--
ALTER TABLE `prediction_result`
  ADD PRIMARY KEY (`prediction_id`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `disease_id` (`disease_id`);

--
-- Indeks untuk tabel `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`user_id`);

--
-- Ketidakleluasaan untuk tabel pelimpahan (Dumped Tables)
--

--
-- Ketidakleluasaan untuk tabel `garden_plants`
--
ALTER TABLE `garden_plants`
  ADD CONSTRAINT `garden_plants_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `garden_plants_ibfk_2` FOREIGN KEY (`plant_id`) REFERENCES `plant_encyclopedia` (`plant_id`) ON DELETE CASCADE;

--
-- Ketidakleluasaan untuk tabel `image`
--
ALTER TABLE `image`
  ADD CONSTRAINT `image_ibfk_1` FOREIGN KEY (`plant_id`) REFERENCES `plant_encyclopedia` (`plant_id`) ON DELETE CASCADE;

--
-- Ketidakleluasaan untuk tabel `plant_diseases`
--
ALTER TABLE `plant_diseases`
  ADD CONSTRAINT `plant_diseases_ibfk_1` FOREIGN KEY (`plant_id`) REFERENCES `plant_encyclopedia` (`plant_id`) ON DELETE CASCADE;

--
-- Ketidakleluasaan untuk tabel `prediction_result`
--
ALTER TABLE `prediction_result`
  ADD CONSTRAINT `prediction_result_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `prediction_result_ibfk_2` FOREIGN KEY (`disease_id`) REFERENCES `plant_diseases` (`disease_id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
